/**********************************************************************************************************************
 * \file ASCLIN_LIN_Master.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin.h"
#include "IfxAsclin_Lin.h"
#include "ASCLIN_LIN_Master.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SERIAL_BAUDRATE     19200                               /* Set the baud rate                                */

#define RX_PIN              IfxAsclin2_RXD_P10_6_IN             /* Set RX port pin                                  */
#define TX_PIN              IfxAsclin2_TX_P10_5_OUT             /* Set TX port pin                                  */

#define MASTER_ID_0x26   0x26
#define SLAVE_ID_0x33    0x33

#define ASCLIN_MASTER_RX         100
#define ASCLIN_MASTER_TX         101
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxAsclin_Lin g_linMaster;
static uint8 HandleID = 0xFF;
static uint8 Rx_data[8] = {0x00};
static uint8 Tx_data[8] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08};
/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the ASCLIN LIN module in master mode */
void init_ASCLIN_LIN_master(void)
{
    /* Initialize one instance of IfxAsclin_Lin_Config with default values */
    IfxAsclin_Lin_Config linMasterConfig;
    IfxAsclin_Lin_initModuleConfig(&linMasterConfig, &MODULE_ASCLIN2);

    linMasterConfig.linMode = IfxAsclin_LinMode_master;         /* Set the LIN mode of operation                    */
    linMasterConfig.brg.baudrate = SERIAL_BAUDRATE;             /* Set the desired baud rate                        */

    const IfxAsclin_Lin_Pins pins =
    {
        &RX_PIN,   IfxPort_InputMode_pullUp,                    /* RX port pin                                      */
        &TX_PIN,   IfxPort_OutputMode_pushPull,                 /* TX port pin                                      */
        IfxPort_PadDriver_cmosAutomotiveSpeed4
    };
    linMasterConfig.pins = &pins;                               /* Port pins configuration                          */

    /* Initialize module */
    IfxAsclin_Lin_initModule(&g_linMaster, &linMasterConfig);
}

void ASCLIN_LIN_Master_Send_Message(void)
{
    uint8 id = MASTER_ID_0x26;
    HandleID = MASTER_ID_0x26;
    /* Send LIN header */
    IfxAsclin_Lin_sendHeader(&g_linMaster, &id); 
}

IFX_INTERRUPT(ISR_ASCLIN_Rx, 0, ASCLIN_MASTER_RX)
{
    /* check Rx response end acknowledgement*/
    if (IfxAsclin_getRxResponseEndFlagStatus(g_linMaster.asclin))
    {
        uint8 id = MASTER_ID_0x26;
        
        IfxAsclin_Lin_clearFlagsStatus(g_linMaster.asclin);
        HandleID = MASTER_ID_0x26;
        IfxAsclin_Lin_sendHeader(&g_linMaster, &id); 
    }

}

IFX_INTERRUPT(ISR_ASCLIN_Tx, 0, ASCLIN_MASTER_TX)
{
      /* check Tx header end acknowledgement */
    if (IfxAsclin_getTxHeaderEndFlagStatus(g_linMaster.asclin)) /* THE flag*/
    {
        if (HandleID == MASTER_ID_0x26)
        {
            IfxAsclin_Lin_sendResponse(&g_linMaster, Tx_data, 8);
        }
        else if(HandleID == SLAVE_ID_0x33)
        {
            IfxAsclin_Lin_receiveResponse(&g_linMaster, Rx_data, 8);

            /* Receive interrupt occurred */
            if (IfxAsclin_getRxFifoFillLevelFlagStatus(g_linMaster.asclin))
            {
                uint8 id = MASTER_ID_0x26;
                HandleID = MASTER_ID_0x26;
                IfxAsclin_Lin_sendHeader(&g_linMaster, &id); 
            }
        }

        IfxAsclin_Lin_clearFlagsStatus(g_linMaster.asclin);
    }

    /* check Tx completed */
    if (IfxAsclin_getTransmissionCompletedFlagStatus(g_linMaster.asclin))
    {
        uint8 id = SLAVE_ID_0x33;
        IfxAsclin_Lin_clearFlagsStatus(g_linMaster.asclin);
        
        HandleID = SLAVE_ID_0x33;
        IfxAsclin_Lin_sendHeader(&g_linMaster, &id); 
    }

}

